import { Component } from '@angular/core';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent {

  value:string | undefined;
  checked:boolean = false;

  customers:any[] =[
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
    ,{
        id: 11,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 12,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 13,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 14,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 15,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 1,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 40,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 2,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 3,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 4,
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 10,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 5,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 30,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 6,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 70,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 7,
        imgSrc: 'assets/Image-30.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 60,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 8,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 90,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },
    {
        id: 9,
        imgSrc: 'assets/Image-30.png',
        name: 'محمد الغريب',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 50,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    },{
        id: 10,
        imgSrc: 'assets/Image-40.png',
        name: 'أحمد محمود',
        phone: '0123456789',
        ticketNo: 'C-101',
        ticketPrice: 20,
        cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
        peopleNo: 1,
        purchaseNo: 'مرة واحدة',
        ticket: 'تذكرة رقم 45.pdf',
    }
];
}
